[tool.poetry]
name = "ramifice"
version = "0.1.0"
description = ""
authors = ["kebasyaty <kebasyaty@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.docs]
optional = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
