[tool.poetry]
name = "ramifice"
version = "0.1.0"
description = ""
authors = ["kebasyaty <kebasyaty@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pymongo = "^4.10.1"
pillow = "^11.0.0"
phonenumbers = "^8.13.52"
email-validator = "^2.2.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocstrings = { extras = ["python"], version = "^0.27.0" }
mkdocs-material = "^9.5.47"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
