[project]
name = "ramifice"
version = "0.3.17"
description = "ORM-like API MongoDB for Python language."
readme = "README.md"
authors = [{ name = "Gennady Kostyunin", email = "kebasyaty@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12,<4.0"
keywords = ["mongo", "mongodb", "pymongo", "orm", "ramifice"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Database",
    "Typing :: Typed",
]
dependencies = [
    "argon2-cffi>=25.1.0",
    "babel>=2.17.0",
    "email-validator>=2.2.0",
    "phonenumbers>=9.0.6",
    "pillow>=11.2.1",
    "pymongo>=4.13.0",
    "python-dateutil>=2.9.0.post0",
    "python-slugify>=8.0.4",
    "pyyaml>=6.0.2",
    "termcolor>=3.1.0",
]

[project.urls]
Homepage = "https://github.com/kebasyaty/ramifice"
Documentation = "https://kebasyaty.github.io/ramifice/"
Repository = "https://github.com/kebasyaty/ramifice"
Source = "https://github.com/kebasyaty/ramifice"
"Bug Tracker" = "https://github.com/kebasyaty/ramifice/issues"
Changelog = "https://github.com/kebasyaty/ramifice/blob/v0/CHANGELOG.md"

[tool.uv]
package = true
default-groups = ["dev", "docs"]
compile-bytecode = true
check-url = "https://pypi.org/simple"

[tool.uv.build-backend]
module-root = "src"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "ruff>=0.11.13",
    "types-python-dateutil>=2.9.0.20250516",
    "types-pyyaml>=6.0.12.20250516",
]
docs = ["mkdocs>=1.6.1", "mkdocs-material>=9.6.14", "mkdocstrings>=0.29.1"]

[tool.ruff]
fix = true
line-length = 100
required-version = ">=0.7.11"
src = ["src", "tests"]
include = [
    "*.py",
    "*.pyi",
    "*.ipynb",
    "**/pyproject.toml",
    "src/**/*.py",
    "tests/**/*.py",
]

[tool.ruff.lint]
select = ["D"]
ignore = ["D417", "D206"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80

[tool.mypy]
strict = true
show_error_codes = true
pretty = true
files = ["*.py", "src/**/*.py", "tests/**/*.py"]
disable_error_code = ["type-arg", "no-any-return"]

[[tool.mypy.overrides]]
module = ["tests.*"]
disable_error_code = [
    "no-untyped-def",
    "no-untyped-call",
    "func-returns-value",
    "attr-defined",
    "arg-type",
    "union-attr",
    "index",
]
