name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "wheels/**"
      - "examples/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "wheels/**"
      - "examples/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-noble

    container:
      image: python:3.13.1
      options: --user root

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: |
          bash .github/workflows/linux-dependencies-install.sh
      - name: Install the project dependencies
        run: poetry install
      - name: Run unittest
        run: |
          poetry run python -m unittest tests/test_mongo.py
          poetry run python -m unittest tests/test_store.py
          poetry run python -m unittest tests/test_tools.py
          poetry run python -m unittest tests/test_types.py
          poetry run python -m unittest discover tests/fields
          poetry run python -m unittest tests/test_model.py
          poetry run python -m unittest tests/test_meta.py
          poetry run python -m unittest tests/test_migration.py

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-noble
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
