name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        mongodb-version: ["8.0"]
        python-version: ["3.12", "3.13"]
        uv-version: ["latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} MongoDB ${{ matrix.mongodb-version }}

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}

      - name: Install dependencies of project
        run: uv sync --locked --no-group docs

      - name: Run checking of code
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run unittest
        run: |
          uv run python -m unittest tests/test_mongo.py
          uv run python -m unittest tests/test_mixins.py
          uv run python -m unittest tests/test_constants.py
          uv run python -m unittest tests/test_tools.py
          uv run python -m unittest tests/test_types.py
          uv run python -m unittest discover -s tests/fields
          uv run python -m unittest tests/test_extra.py
          uv run python -m unittest tests/test_migration.py
          uv run python -m unittest tests/test_fixtures.py
          uv run python -m unittest discover -s tests/paladins
          uv run python -m unittest discover -s tests/commons
          uv run python -m unittest discover -s tests/models
          uv run python -m unittest tests/test_translations.py

  success:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo Test Successful
