name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "wheels/**"
      - "examples/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "wheels/**"
      - "examples/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        mongodb-version: ["6.0", "7.0", "8.0"]
        python-version: ["3.12", "3.13"]
        poetry-version: ["latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }} MongoDB ${{ matrix.mongodb-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file.
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Run unittest
        run: |
          poetry run python -m unittest tests/test_mongo.py
          poetry run python -m unittest tests/test_mixins.py
          poetry run python -m unittest tests/test_store.py
          poetry run python -m unittest tests/test_tools.py
          poetry run python -m unittest tests/test_types.py
          poetry run python -m unittest discover tests/fields
          poetry run python -m unittest tests/test_model.py
          poetry run python -m unittest tests/test_meta.py
          poetry run python -m unittest tests/test_migration.py

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ${{ matrix.os }}
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
